"""Initial migration for PostgreSQL

Revision ID: 0e66395642f7
Revises: 
Create Date: 2024-10-24 11:42:10.384494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '0e66395642f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создание таблицы contacts, если она не существует
    if not table_exists('contacts'):
        op.create_table('contacts',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('address', sa.Text(), nullable=True),
                        sa.Column('correspondence_address', sa.Text(), nullable=True),
                        sa.Column('email', sa.String(), nullable=True),
                        sa.Column('phones', sa.Text(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)

    # Создание таблицы main_article, если она не существует
    if not table_exists('main_article'):
        op.create_table('main_article',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_main_article_id'), 'main_article', ['id'], unique=False)

    # Создание таблицы news, если она не существует
    if not table_exists('news'):
        op.create_table('news',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('url', sa.Text(), nullable=True),
                        sa.Column('title', sa.String(), nullable=True),
                        sa.Column('title_arabian', sa.String(), nullable=True),
                        sa.Column('subtitle', sa.String(), nullable=True),
                        sa.Column('subtitle_arabian', sa.String(), nullable=True),
                        sa.Column('tag', sa.String(), nullable=True),
                        sa.Column('tag_arabian', sa.String(), nullable=True),
                        sa.Column('updated', sa.String(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)

    # Создание таблицы partners, если она не существует
    if not table_exists('partners'):
        op.create_table('partners',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('url', sa.Text(), nullable=True),
                        sa.Column('title', sa.String(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)

    # Создание таблицы users, если она не существует
    if not table_exists('users'):
        op.create_table('users',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('username', sa.String(), nullable=True),
                        sa.Column('password', sa.String(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_main_article_id'), table_name='main_article')
    op.drop_table('main_article')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
